defmodule Receipts.Repo.Migrations.InitialResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:lol_players, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:name, :text, null: false)
      add(:discord_id, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:lol_players, [:discord_id],
        name: "lol_players_unique_discord_id_index",
        nulls_distinct: false
      )
    )

    create table(:lol_matches, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:riot_match_id, :text, null: false)
      add(:game_datetime, :utc_datetime_usec, null: false)
      add(:game_duration_seconds, :bigint)
      add(:queue_id, :bigint)
      add(:raw_info, :map)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      unique_index(:lol_matches, [:riot_match_id], name: "lol_matches_unique_match_id_index")
    )

    create table(:lol_match_participants, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:kills, :bigint)
      add(:deaths, :bigint)
      add(:assists, :bigint)
      add(:win, :boolean)
      add(:cs, :bigint)
      add(:damage_dealt, :bigint)
      add(:vision_score, :bigint)
      add(:position, :text)
      add(:items, {:array, :bigint}, default: [])
      add(:raw_participant, :map)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :match_id,
        references(:lol_matches,
          column: :id,
          name: "lol_match_participants_match_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:account_id, :uuid, null: false)
      add(:champion_id, :uuid, null: false)
    end

    create(
      unique_index(:lol_match_participants, [:account_id, :match_id],
        name: "lol_match_participants_unique_account_match_index"
      )
    )

    create table(:lol_champions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:riot_id, :bigint, null: false)
      add(:name, :text, null: false)
      add(:key, :text, null: false)
      add(:image, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(unique_index(:lol_champions, [:key], name: "lol_champions_unique_key_index"))

    create(unique_index(:lol_champions, [:riot_id], name: "lol_champions_unique_riot_id_index"))

    create table(:lol_accounts, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:lol_match_participants) do
      modify(
        :account_id,
        references(:lol_accounts,
          column: :id,
          name: "lol_match_participants_account_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :champion_id,
        references(:lol_champions,
          column: :id,
          name: "lol_match_participants_champion_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:lol_accounts) do
      add(:riot_puuid, :text, null: false)
      add(:riot_game_name, :text)
      add(:riot_tag_line, :text)
      add(:riot_region, :text, null: false)
      add(:riot_routing, :text, null: false)
      add(:newest_synced_at, :utc_datetime_usec)
      add(:oldest_synced_start, :bigint, default: 0)
      add(:history_fully_synced, :boolean, default: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :player_id,
        references(:lol_players,
          column: :id,
          name: "lol_accounts_player_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    create(unique_index(:lol_accounts, [:riot_puuid], name: "lol_accounts_unique_puuid_index"))
  end

  def down do
    drop(constraint(:lol_accounts, "lol_accounts_player_id_fkey"))

    drop_if_exists(
      unique_index(:lol_accounts, [:riot_puuid], name: "lol_accounts_unique_puuid_index")
    )

    alter table(:lol_accounts) do
      remove(:player_id)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:history_fully_synced)
      remove(:oldest_synced_start)
      remove(:newest_synced_at)
      remove(:riot_routing)
      remove(:riot_region)
      remove(:riot_tag_line)
      remove(:riot_game_name)
      remove(:riot_puuid)
    end

    drop(constraint(:lol_match_participants, "lol_match_participants_account_id_fkey"))

    drop(constraint(:lol_match_participants, "lol_match_participants_champion_id_fkey"))

    alter table(:lol_match_participants) do
      modify(:champion_id, :uuid)
      modify(:account_id, :uuid)
    end

    drop(table(:lol_accounts))

    drop_if_exists(
      unique_index(:lol_champions, [:riot_id], name: "lol_champions_unique_riot_id_index")
    )

    drop_if_exists(unique_index(:lol_champions, [:key], name: "lol_champions_unique_key_index"))

    drop(table(:lol_champions))

    drop(constraint(:lol_match_participants, "lol_match_participants_match_id_fkey"))

    drop_if_exists(
      unique_index(:lol_match_participants, [:account_id, :match_id],
        name: "lol_match_participants_unique_account_match_index"
      )
    )

    drop(table(:lol_match_participants))

    drop_if_exists(
      unique_index(:lol_matches, [:riot_match_id], name: "lol_matches_unique_match_id_index")
    )

    drop(table(:lol_matches))

    drop_if_exists(
      unique_index(:lol_players, [:discord_id], name: "lol_players_unique_discord_id_index")
    )

    drop(table(:lol_players))
  end
end
