defmodule Receipts.Repo.Migrations.FixPlayerDiscordIdNilDistinct do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      unique_index(:lol_players, [:discord_id], name: "lol_players_unique_discord_id_index")
    )

    create(unique_index(:lol_players, [:discord_id], name: "lol_players_unique_discord_id_index"))
  end

  def down do
    drop_if_exists(
      unique_index(:lol_players, [:discord_id], name: "lol_players_unique_discord_id_index")
    )

    create(
      unique_index(:lol_players, [:discord_id],
        name: "lol_players_unique_discord_id_index",
        nulls_distinct: false
      )
    )
  end
end
