defmodule Receipts.Repo.Migrations.RemapOtherQueueTypes do
  use Ecto.Migration

  def up do
    # Update lol_matches with the full queue_id → queue_type mapping
    execute("""
    UPDATE lol_matches SET queue_type = CASE queue_id
      WHEN 0    THEN 'custom'
      WHEN 2    THEN 'normal_blind'
      WHEN 4    THEN 'ranked_solo'
      WHEN 6    THEN 'ranked_premade'
      WHEN 7    THEN 'bot'
      WHEN 8    THEN 'twisted_treeline'
      WHEN 9    THEN 'twisted_treeline'
      WHEN 14   THEN 'normal_draft'
      WHEN 16   THEN 'dominion'
      WHEN 17   THEN 'dominion'
      WHEN 25   THEN 'dominion'
      WHEN 31   THEN 'bot'
      WHEN 32   THEN 'bot'
      WHEN 33   THEN 'bot'
      WHEN 41   THEN 'twisted_treeline'
      WHEN 42   THEN 'ranked_team'
      WHEN 52   THEN 'bot'
      WHEN 61   THEN 'team_builder'
      WHEN 65   THEN 'aram'
      WHEN 67   THEN 'bot'
      WHEN 70   THEN 'one_for_all'
      WHEN 72   THEN 'snowdown'
      WHEN 73   THEN 'snowdown'
      WHEN 75   THEN 'hexakill'
      WHEN 76   THEN 'urf'
      WHEN 78   THEN 'one_for_all'
      WHEN 83   THEN 'urf'
      WHEN 91   THEN 'doom_bots'
      WHEN 92   THEN 'doom_bots'
      WHEN 93   THEN 'doom_bots'
      WHEN 96   THEN 'ascension'
      WHEN 98   THEN 'hexakill'
      WHEN 100  THEN 'aram'
      WHEN 300  THEN 'poro_king'
      WHEN 310  THEN 'nemesis'
      WHEN 313  THEN 'black_market_brawlers'
      WHEN 315  THEN 'nexus_siege'
      WHEN 317  THEN 'dominion'
      WHEN 318  THEN 'urf'
      WHEN 325  THEN 'all_random'
      WHEN 400  THEN 'normal_draft'
      WHEN 410  THEN 'ranked_dynamic'
      WHEN 420  THEN 'ranked_solo'
      WHEN 430  THEN 'normal_blind'
      WHEN 440  THEN 'ranked_flex'
      WHEN 450  THEN 'aram'
      WHEN 460  THEN 'twisted_treeline'
      WHEN 470  THEN 'twisted_treeline'
      WHEN 480  THEN 'swiftplay'
      WHEN 490  THEN 'quickplay'
      WHEN 600  THEN 'blood_hunt'
      WHEN 610  THEN 'dark_star'
      WHEN 700  THEN 'clash'
      WHEN 720  THEN 'aram_clash'
      WHEN 800  THEN 'bot'
      WHEN 810  THEN 'bot'
      WHEN 820  THEN 'bot'
      WHEN 830  THEN 'bot'
      WHEN 840  THEN 'bot'
      WHEN 850  THEN 'bot'
      WHEN 870  THEN 'bot'
      WHEN 880  THEN 'bot'
      WHEN 890  THEN 'bot'
      WHEN 900  THEN 'urf'
      WHEN 910  THEN 'ascension'
      WHEN 920  THEN 'poro_king'
      WHEN 940  THEN 'nexus_siege'
      WHEN 950  THEN 'doom_bots'
      WHEN 960  THEN 'doom_bots'
      WHEN 980  THEN 'star_guardian'
      WHEN 990  THEN 'star_guardian'
      WHEN 1000 THEN 'project_hunters'
      WHEN 1010 THEN 'urf'
      WHEN 1020 THEN 'one_for_all'
      WHEN 1030 THEN 'odyssey'
      WHEN 1040 THEN 'odyssey'
      WHEN 1050 THEN 'odyssey'
      WHEN 1060 THEN 'odyssey'
      WHEN 1070 THEN 'odyssey'
      WHEN 1090 THEN 'tft'
      WHEN 1100 THEN 'tft'
      WHEN 1110 THEN 'tft'
      WHEN 1111 THEN 'tft'
      WHEN 1200 THEN 'nexus_blitz'
      WHEN 1210 THEN 'tft'
      WHEN 1300 THEN 'nexus_blitz'
      WHEN 1400 THEN 'ultimate_spellbook'
      WHEN 1700 THEN 'arena'
      WHEN 1710 THEN 'arena'
      WHEN 1810 THEN 'swarm'
      WHEN 1820 THEN 'swarm'
      WHEN 1830 THEN 'swarm'
      WHEN 1840 THEN 'swarm'
      WHEN 1900 THEN 'urf'
      WHEN 2000 THEN 'tutorial'
      WHEN 2010 THEN 'tutorial'
      WHEN 2020 THEN 'tutorial'
      WHEN 2300 THEN 'brawl'
      WHEN 2400 THEN 'aram'
      ELSE 'other'
    END
    """)

    # Re-sync queue_type onto participants from the updated matches
    execute("""
    UPDATE lol_match_participants mp
    SET queue_type = m.queue_type
    FROM lol_matches m
    WHERE mp.match_id = m.id
      AND mp.queue_type != m.queue_type
    """)
  end

  def down, do: :ok
end
