defmodule Receipts.Repo.Migrations.AddQueueTypeToMatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:lol_matches) do
      add(:queue_type, :text)
    end

    execute("""
    UPDATE lol_matches SET queue_type = CASE queue_id
      WHEN 0    THEN 'custom'
      WHEN 400  THEN 'normal_draft'
      WHEN 420  THEN 'ranked_solo'
      WHEN 430  THEN 'normal_blind'
      WHEN 440  THEN 'ranked_flex'
      WHEN 450  THEN 'aram'
      WHEN 700  THEN 'clash'
      WHEN 720  THEN 'aram_clash'
      WHEN 900  THEN 'urf'
      WHEN 1020 THEN 'one_for_all'
      WHEN 1300 THEN 'nexus_blitz'
      WHEN 1400 THEN 'ultimate_spellbook'
      WHEN 1700 THEN 'arena'
      WHEN 1900 THEN 'urf'
      WHEN 2000 THEN 'tutorial'
      WHEN 2010 THEN 'tutorial'
      WHEN 2020 THEN 'tutorial'
      ELSE 'other'
    END
    """)

    create(index(:lol_matches, [:queue_type]))
  end

  def down do
    drop_if_exists(index(:lol_matches, [:queue_type]))

    alter table(:lol_matches) do
      remove(:queue_type)
    end
  end
end
