defmodule Receipts.Repo.Migrations.AddTeamIdAndIndexes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create(index(:lol_matches, [:game_datetime]))

    alter table(:lol_match_participants) do
      add(:team_id, :bigint)
    end

    execute("""
    UPDATE lol_match_participants
    SET team_id = (raw_participant->>'teamId')::bigint
    WHERE raw_participant IS NOT NULL
    """)

    create(index(:lol_match_participants, [:match_id, :team_id]))

    create(index(:lol_match_participants, [:account_id, :champion_id]))
  end

  def down do
    drop_if_exists(index(:lol_match_participants, [:account_id, :champion_id]))

    drop_if_exists(index(:lol_match_participants, [:match_id, :team_id]))

    alter table(:lol_match_participants) do
      remove(:team_id)
    end

    drop_if_exists(index(:lol_matches, [:game_datetime]))
  end
end
